name: "default"
type: "causal_lm"
provider: "vllm"
device: "auto"
batch_size: 8
max_gen_toks: 512
quantized: null
padding_side: "right"
trust_remote_code: true
gpu_memory_utilization: 0.5
max_model_len: 4096
max_cudagraph_capture_size: 16
enforce_eager: true
language_model_only: true
tensor_parallel_size: 1
disable_custom_all_reduce: true
attention_backend: "TRITON_ATTN"
generation_args: {
    "temperature": 0.0,
    "top_p": 1.0
}
